import pygal

pie_chart = pygal.Pie()
pie_chart.title = 'Programming Language Popularity in September 2018 (in %)'
pie_chart.add('Python', 24.58)
pie_chart.add('Java', 22.14)
pie_chart.add('Javascript', 8.41)
pie_chart.add('PHP', 7.77)
pie_chart.add('C#', 7.74)
pie_chart.add('C/C++', 6.22)
pie_chart.add('R', 4.04)
pie_chart.add('Objective-C', 3.33)
pie_chart.add('Swift', 2.65)
pie_chart.add('Matlab', 2.1)
pie_chart.add('Ruby', 1.62)
pie_chart.add('TypeScript', 1.57)
pie_chart.add('VBA', 1.49)
pie_chart.add('Scala', 1.23)
pie_chart.add('Visual Basic', 1.11)
pie_chart.add('Kotlin', 1.02)
pie_chart.add('Go', 0.94)
pie_chart.add('Perl', 0.7)
pie_chart.add('Lua', 0.38)
pie_chart.add('Rust', 0.38)
pie_chart.add('Haskell', 0.3)
pie_chart.add('Delphi', 0.25)
pie_chart.render_to_file('pop_lang_piechart.svg')
